name: 'Push Commit Labeler'
description: 'Add label to your issues using push commit messages. Just use on your commit message the following syntax "%YOUR_LABEL% #issue_number" to apply labels using commit messages'
author: 'Fabio Luis Girardi'
branding:
  icon: tag
  color: yellow

inputs:
  github-token:
    description: 'GITHUB_TOKEN or a `repo` scoped Personal Access Token (PAT)'
    required: false
    default: ${{ github.token }}

runs:
  using: 'node12'
  main: 'main.ts'
